"""Build an oversampled train split for RFS/IRFS class-imbalance sampling.

Usage:
    python scripts/build_oversampled_split.py --mode rfs --target-classes bike motor
    python scripts/build_oversampled_split.py --mode irfs --target-classes bike motor

Reads the existing train_100 split + label files (read-only - never touches
dataset/yolo/images or dataset/yolo/labels), computes per-image repeat
factors via compute_repeat_factors.py, and writes:
  - a new split list (dataset/yolo/splits/train_100_<mode>.txt): the
    original bare filenames, each repeated per its stochastically-rounded
    repeat count. This mirrors train_100.txt's own convention (a flat list
    resolved to absolute paths by resolve_splits.py before training), so no
    image/label files are ever copied or symlinked.
  - a dataset yaml (dataset/bdd100k_vehicle_<mode>.yaml): train: points at
    the new split's resolved path; val:/names: copied unchanged from
    --base-dataset-yaml.
  - an experiment config (configs/experiments/<arm_name>.yaml): default
    Ultralytics training hyperparameters, no augmentation overrides -
    Method 2 tests sampling in isolation.
  - a before/after class-distribution report (JSON) under
    results/sampling_reports/.

Must be run from the repo root. Run scripts/resolve_splits.py afterward (or
scripts/train_arm.py, which calls it automatically) to materialize
splits/train_100_<mode>_resolved.txt before training.
"""

import argparse
import json
from pathlib import Path

import yaml

import compute_repeat_factors as rf

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_LABELS_DIR = ROOT / "dataset" / "yolo" / "labels" / "train"
DEFAULT_SPLIT_LIST = ROOT / "dataset" / "yolo" / "splits" / "train_100.txt"
DEFAULT_SPLITS_OUT_DIR = ROOT / "dataset" / "yolo" / "splits"
DEFAULT_BASE_DATASET_YAML = ROOT / "dataset" / "bdd100k_vehicle.yaml"
DEFAULT_DATASET_YAML_OUT_DIR = ROOT / "dataset"
DEFAULT_CONFIG_OUT_DIR = ROOT / "configs" / "experiments"
DEFAULT_REPORT_OUT_DIR = ROOT / "results" / "sampling_reports"

EVAL_SPLITS = [
    {"name": "val_day", "data": "dataset/bdd100k_test_day.yaml"},
    {"name": "val_night", "data": "dataset/bdd100k_test_night.yaml"},
    {"name": "val_dawndusk", "data": "dataset/bdd100k_test_dawndusk.yaml"},
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--mode", required=True, choices=["rfs", "irfs"])
    parser.add_argument("--threshold", type=float, default=0.001, help="t in r_c = max(1, sqrt(t/f_c)). Default 1e-3.")
    parser.add_argument("--seed", type=int, default=42, help="Seed for stochastic rounding.")
    parser.add_argument(
        "--target-classes",
        nargs="+",
        default=None,
        metavar="CLASS",
        help="Restrict oversampling to these class names (e.g. bike motor). "
        "Classes outside this list are always forced to r_c=1 (never oversampled), "
        "though their frequency is still measured and reported. "
        "Default: None -> standard full RFS/IRFS over all classes.",
    )
    parser.add_argument("--labels-dir", type=Path, default=DEFAULT_LABELS_DIR)
    parser.add_argument("--split-list", type=Path, default=DEFAULT_SPLIT_LIST)
    parser.add_argument("--base-dataset-yaml", type=Path, default=DEFAULT_BASE_DATASET_YAML)
    parser.add_argument("--splits-out-dir", type=Path, default=DEFAULT_SPLITS_OUT_DIR)
    parser.add_argument("--dataset-yaml-out-dir", type=Path, default=DEFAULT_DATASET_YAML_OUT_DIR)
    parser.add_argument("--config-out-dir", type=Path, default=DEFAULT_CONFIG_OUT_DIR)
    parser.add_argument("--report-out-dir", type=Path, default=DEFAULT_REPORT_OUT_DIR)
    parser.add_argument("--arm-name", default=None, help="Default: method2_<mode>_sampling")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--workers", type=int, default=2)
    return parser.parse_args()


def write_split_list(image_names: list[str], repeat_counts: dict[str, int], out_path: Path) -> int:
    lines = []
    for name in image_names:  # preserve train_100.txt's original ordering
        lines.extend([name] * repeat_counts[name])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(lines)


def write_dataset_yaml(base_yaml_path: Path, mode: str, split_stem: str, base_yaml: dict, out_path: Path) -> None:
    lines = [
        f"# Auto-generated by scripts/build_oversampled_split.py --mode {mode}.",
        f"# train: oversampled split for class-imbalance sampling (Method 2).",
        f"# val/names copied unchanged from {base_yaml_path.name}.",
        f"path: {base_yaml['path']}",
        "",
        f"train: splits/{split_stem}_resolved.txt",
        f"val: {base_yaml['val']}",
        "",
        "names:",
    ]
    for class_id, class_name in sorted(base_yaml["names"].items()):
        lines.append(f"  {class_id}: {class_name}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_experiment_config(
    arm_name: str,
    dataset_yaml_rel: str,
    epochs: int,
    imgsz: int,
    batch: int,
    workers: int,
    seed: int,
    out_path: Path,
) -> None:
    lines = [
        f"arm_name: {arm_name}",
        "model: yolo11s.pt",
        f"data: {dataset_yaml_rel}",
        "",
        "train:",
        f"  epochs: {epochs}",
        f"  seed: {seed}",
        f"  imgsz: {imgsz}",
        f"  batch: {batch}",
        f"  workers: {workers}",
        "  cache: false",
        "  patience: 0  # disable early stopping so every arm trains the full run",
        f"  name: {arm_name}",
        f"  exist_ok: true  # rerunning this arm overwrites runs/detect/{arm_name} rather than incrementing",
        "",
        "eval_splits:",
    ]
    for split in EVAL_SPLITS:
        lines.append(f"  - name: {split['name']}")
        lines.append(f"    data: {split['data']}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_distribution_report(
    counts: rf.ClassCounts,
    class_factors: dict[int, dict[str, float]],
    repeat_counts: dict[str, int],
    mode: str,
    threshold: float,
    seed: int,
    target_classes: list[str] | None,
) -> dict:
    class_names = counts.class_names
    before_images = {c: 0 for c in class_names}
    before_instances = {c: 0 for c in class_names}
    for classes in counts.per_image_classes.values():
        for c, n in classes.items():
            before_images[c] += 1
            before_instances[c] += n

    after_images = {c: 0 for c in class_names}
    after_instances = {c: 0 for c in class_names}
    for image_name, classes in counts.per_image_classes.items():
        rep = repeat_counts[image_name]
        for c, n in classes.items():
            after_images[c] += rep
            after_instances[c] += n * rep

    target_set = set(target_classes) if target_classes else None
    per_class = {}
    for c, name in sorted(class_names.items()):
        entry = {k: v for k, v in class_factors[c].items() if k != "r_c"}
        entry["repeat_factor_r_c"] = class_factors[c]["r_c"]
        entry["image_count_before"] = before_images[c]
        entry["instance_count_before"] = before_instances[c]
        entry["image_count_after"] = after_images[c]
        entry["instance_count_after"] = after_instances[c]
        per_class[name] = entry

    return {
        "mode": mode,
        "threshold": threshold,
        "seed": seed,
        "restricted_to": sorted(target_set) if target_set else None,
        "excluded_classes_forced_r1": sorted(set(class_names.values()) - target_set) if target_set else [],
        "total_images_before": len(counts.image_names),
        "total_images_after": sum(repeat_counts.values()),
        "per_class": per_class,
    }


def main() -> None:
    args = parse_args()
    arm_name = args.arm_name or f"method2_{args.mode}_sampling"

    base_yaml = yaml.safe_load(args.base_dataset_yaml.read_text(encoding="utf-8"))
    class_names = {int(k): v for k, v in base_yaml["names"].items()}

    counts = rf.load_class_counts(args.labels_dir, args.split_list, class_names)

    if args.mode == "rfs":
        class_factors = rf.compute_rfs_factors(counts, args.threshold, args.target_classes)
    else:
        class_factors = rf.compute_irfs_factors(counts, args.threshold, args.target_classes)

    image_r = rf.compute_image_repeat_factors(counts, class_factors)
    repeat_counts = rf.compute_repeat_counts(image_r, seed=args.seed)

    split_stem = f"train_100_{args.mode}"
    split_out = args.splits_out_dir / f"{split_stem}.txt"
    n_lines = write_split_list(counts.image_names, repeat_counts, split_out)

    dataset_yaml_out = args.dataset_yaml_out_dir / f"bdd100k_vehicle_{args.mode}.yaml"
    write_dataset_yaml(args.base_dataset_yaml, args.mode, split_stem, base_yaml, dataset_yaml_out)

    config_out = args.config_out_dir / f"{arm_name}.yaml"
    dataset_yaml_rel = dataset_yaml_out.relative_to(ROOT).as_posix()
    write_experiment_config(
        arm_name, dataset_yaml_rel, args.epochs, args.imgsz, args.batch, args.workers, args.seed, config_out
    )

    report = build_distribution_report(
        counts, class_factors, repeat_counts, args.mode, args.threshold, args.seed, args.target_classes
    )
    report_out = args.report_out_dir / f"{args.mode}_distribution.json"
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"[{args.mode}] wrote {n_lines} lines ({len(counts.image_names)} unique images) -> {split_out.relative_to(ROOT)}")
    print(f"[{args.mode}] dataset yaml -> {dataset_yaml_out.relative_to(ROOT)}")
    print(f"[{args.mode}] experiment config -> {config_out.relative_to(ROOT)}")
    print(f"[{args.mode}] distribution report -> {report_out.relative_to(ROOT)}")
    print(
        f"Reminder: run scripts/resolve_splits.py (or scripts/train_arm.py, which calls it "
        f"automatically) before training, to materialize splits/{split_stem}_resolved.txt."
    )


if __name__ == "__main__":
    main()
