#!/usr/bin/env python3
"""Build per-condition TEST slices (time-of-day x weather) from splits/test.txt.

Project scope moved from "low light" to "adverse environment" (2026-09), so the
held-out test set now needs to be sliceable by weather as well as by time of
day, plus a few crossed slices that separate "it is dark" from "the weather is
bad".

Deterministic: pure function of splits/test.txt + dataset/yolo/attr_index.json.
No sampling, no seed. Every image in test.txt lands in exactly one timeofday
slice and exactly one weather slice.

Writes three things per slice:
  splits/test_slices/<slice>.txt          bare filenames  (portable, commit this)
  dataset/yolo/splits/test_<slice>.txt    repo-relative image paths (what ultralytics reads)
  configs/data/bdd100k_test_<slice>.yaml  data config pointing val: at that list

plus splits/test_slices/MANIFEST.json with image + per-class instance counts.

Usage:
  python tools/make_test_slices.py
  python tools/make_test_slices.py --min-images 200   # only emit yamls for usable slices
"""
import argparse
import json
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# slice name -> (timeofday set or None, weather set or None)
TOD = {"daytime", "night", "dawn/dusk"}
WEA = {"clear", "overcast", "partly cloudy", "snowy", "rainy", "foggy"}

SLICES = {
    # time of day (partition)
    "day":            ({"daytime"},   None),
    "night":          ({"night"},     None),
    "dawndusk":       ({"dawn/dusk"}, None),
    # weather (partition)
    "clear":          (None, {"clear"}),
    "overcast":       (None, {"overcast"}),
    "partlycloudy":   (None, {"partly cloudy"}),
    "snowy":          (None, {"snowy"}),
    "rainy":          (None, {"rainy"}),
    "foggy":          (None, {"foggy"}),
    # composites
    "adverse":        (None, {"rainy", "snowy", "foggy"}),
    "benign":         (None, {"clear", "overcast", "partly cloudy"}),
    # crossed: separates darkness from weather
    "night_clear":    ({"night"},   {"clear"}),
    "night_rainy":    ({"night"},   {"rainy"}),
    "night_snowy":    ({"night"},   {"snowy"}),
    "night_adverse":  ({"night"},   {"rainy", "snowy", "foggy"}),
    "day_clear":      ({"daytime"}, {"clear"}),
    "day_rainy":      ({"daytime"}, {"rainy"}),
    "day_snowy":      ({"daytime"}, {"snowy"}),
    "day_adverse":    ({"daytime"}, {"rainy", "snowy", "foggy"}),
}

YAML_TEMPLATE = """# AUTO-GENERATED by tools/make_test_slices.py - do not edit by hand.
# Held-out TEST slice: {desc}
# {n} images. Scoring only - never train or tune on these.
# path/names copied from bdd100k_vehicle5.yaml so every slice scores identically.
path: dataset/yolo
train: splits/train_100.txt   # unused for scoring; present so ultralytics accepts the yaml
val: splits/test_{slug}.txt

names:
  0: car
  1: truck
  2: bus
  3: motor
  4: bike
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--test-list", default="splits/test.txt")
    ap.add_argument("--attr-index", default="dataset/yolo/attr_index.json")
    ap.add_argument("--labels-dir", default="dataset/yolo/labels/val",
                    help="GT labels for the test pool (BDD official val)")
    ap.add_argument("--images-prefix", default="dataset/yolo/images/val")
    ap.add_argument("--min-images", type=int, default=0,
                    help="emit a WARNING for slices below this many images")
    args = ap.parse_args()

    attrs = json.load(open(REPO / args.attr_index))
    names = [l.strip() for l in open(REPO / args.test_list) if l.strip()]
    names = [Path(n).name for n in names]

    labels_dir = REPO / args.labels_dir
    class_names = ["car", "truck", "bus", "motor", "bike"]

    def instances(sel):
        c = Counter()
        for n in sel:
            f = labels_dir / (Path(n).stem + ".txt")
            if not f.exists():
                continue
            for line in f.read_text().splitlines():
                if line.strip():
                    c[int(line.split()[0])] += 1
        return {class_names[i]: c.get(i, 0) for i in range(len(class_names))}

    have_labels = labels_dir.is_dir()
    if not have_labels:
        print(f"NOTE: {labels_dir} not present - writing lists/yamls, skipping instance counts.")

    (REPO / "splits" / "test_slices").mkdir(parents=True, exist_ok=True)
    (REPO / "dataset" / "yolo" / "splits").mkdir(parents=True, exist_ok=True)
    (REPO / "configs" / "data").mkdir(parents=True, exist_ok=True)

    # sanity: attribute vocabulary is what we think it is
    tods = {attrs[n]["timeofday"] for n in names}
    weas = {attrs[n]["weather"] for n in names}
    assert tods <= TOD, f"unexpected timeofday values: {tods - TOD}"
    assert weas <= WEA, f"unexpected weather values: {weas - WEA}"

    manifest = {"source_list": args.test_list, "total_images": len(names), "slices": {}}
    for slug, (tod, wea) in SLICES.items():
        sel = [n for n in names
               if (tod is None or attrs[n]["timeofday"] in tod)
               and (wea is None or attrs[n]["weather"] in wea)]
        desc = " + ".join(filter(None, [
            "/".join(sorted(tod)) if tod else "",
            "/".join(sorted(wea)) if wea else "",
        ])) or "all"

        (REPO / "splits" / "test_slices" / f"{slug}.txt").write_text(
            "".join(n + "\n" for n in sel))
        (REPO / "dataset" / "yolo" / "splits" / f"test_{slug}.txt").write_text(
            "".join(f"{args.images_prefix}/{n}\n" for n in sel))
        (REPO / "configs" / "data" / f"bdd100k_test_{slug}.yaml").write_text(
            YAML_TEMPLATE.format(desc=desc, n=len(sel), slug=slug))

        row = {"images": len(sel), "timeofday": sorted(tod) if tod else "any",
               "weather": sorted(wea) if wea else "any"}
        if have_labels:
            row["instances"] = instances(sel)
            row["instances_total"] = sum(row["instances"].values())
        manifest["slices"][slug] = row

        warn = "  <-- TOO FEW, do not report mAP" if 0 < len(sel) < max(args.min_images, 1) else ""
        print(f"{slug:<15} {len(sel):>6} images"
              + (f"  {row.get('instances_total', ''):>7} instances" if have_labels else "")
              + warn)

    # partition checks
    p_tod = sum(manifest["slices"][s]["images"] for s in ("day", "night", "dawndusk"))
    p_wea = sum(manifest["slices"][s]["images"]
                for s in ("clear", "overcast", "partlycloudy", "snowy", "rainy", "foggy"))
    assert p_tod == len(names), f"timeofday slices sum to {p_tod}, expected {len(names)}"
    assert p_wea == len(names), f"weather slices sum to {p_wea}, expected {len(names)}"
    assert (manifest["slices"]["adverse"]["images"]
            + manifest["slices"]["benign"]["images"] == len(names))
    manifest["partition_checks"] = {"timeofday_sum": p_tod, "weather_sum": p_wea,
                                    "total": len(names), "ok": True}

    (REPO / "splits" / "test_slices" / "MANIFEST.json").write_text(
        json.dumps(manifest, indent=2))
    print(f"\nOK - timeofday and weather slices each partition all {len(names)} test images.")
    print(f"wrote splits/test_slices/, dataset/yolo/splits/test_*.txt, "
          f"configs/data/bdd100k_test_*.yaml")


if __name__ == "__main__":
    main()
